### ISSUE TITLE
neurolyzer macchanger doesn't work on rtl8812au

### ISSUE THREAD

**Issue by amenekowo** [AlienMajik/pwnagotchi_plugins#1]
Hi! I'm running my pwnagotchi on kali x86 rolling and I'm using RTL8812AU.
I noticed I couldn't change mac address on the fly, if I don't down wlan0mon first:
```
┌──(pastel_parasol㉿-)-[~]
└─$ sudo macchanger -r wlan0mon
Current MAC:   xx:xx:xx:xx:xx:xx (unknown)
Permanent MAC: xx:xx:xx:xx:xx:xx (unknown)
[ERROR] Could not change MAC: interface up or insufficient permissions: Operation not permitted
```

```
┌──(root㉿-)-[/home/pastel_parasol]
└─# macchanger -r wlan0mon
Current MAC:  xx:xx:xx:xx:xx:xx (unknown)
Permanent MAC: xx:xx:xx:xx:xx:xx (unknown)
New MAC:       8e:88:c7:75:b9:fa (unknown)

```

I don't have a raspberry pi near my hand so I can't do the test.
I will add ifdown&up in the plugins and see if it makes difference. After some testing, I will find out.

Thanks for your awesome plugin and have a nice day :3

**Comment by AlienMajik** [comment]
when you first install macchanger, it can be configured to automatically randomize the MAC address every time a network interface is brought up or plugged in. However, this behavior is not enabled by default. You can modify system configurations to achieve this by following these steps:

	1.	Edit the Network Interface Configuration:
You can modify /etc/network/interfaces or create a script to execute macchanger automatically whenever an interface is brought up.
	2.	For Ethernet or Wi-Fi Interfaces:
You could add commands to /etc/network/interfaces for each specific network interface (e.g., wlan0, eth0):

iface wlan0 inet dhcp
pre-up macchanger -r wlan0

This will randomize the MAC address using macchanger before the interface is brought up.

	3.	Using Udev Rules:
You can create a udev rule that will run macchanger whenever a device is plugged in or brought up.
Create a new udev rule in /etc/udev/rules.d/70-macchanger.rules:

ACTION=="add", SUBSYSTEM=="net", KERNEL=="wlan0", RUN+="/usr/bin/macchanger -r wlan0"

This rule tells udev to run macchanger whenever a network device (wlan0 in this case) is added.

If you don’t have these automated steps configured, you’d need to run macchanger manually or incorporate it into your workflow, like you’re doing with your plugins for Pwnagotchi.

**Comment by AlienMajik** [comment]
I find it easier to just uninstall macchanger reboot then reinstall it
